* Prelimeraries
* Who I am
** Naval Officer
 - Five year career as a Naval Officer
** Aspiring Engineer
 - Studied in college
 - Wish to return
** Specific Interest
 - How I found your job
 - Why I'm interested
* Why I'm qualified
** Experienced worker
 - Diverse track record
 - Autonomous
 - Teamwork
** Detail Orientated
 - Navy taught me the importance of follow-through 
** Follow directions
 - Took vague directions and produced detailed results
   - This is what the military is all about
** Learn quickly
 - The Navy expects officers to always be qualifying for the next level and to be learning their boss's job. I excelled at this process inside of the Navy and have always been seeking new skill sets in my personal life. 
 - Please let me know if I lack any specific skills required for this job. Likely, I can arrange to learn them.
* Moving Forward
** Interview me
 - I promise to impress.
 - I want to discuss my qualifications and our mutual goals.
   I respectfully request you invite me for an interview to discuss my qualifications and our mutual goals. I promise to impress.
** Contact me
 - How to contact me
   For the next month, I am out of the country and will only be contactable via email. If necessary, I can arrange a phone or skype interview. Otherwise, I will be available for in person meetings in early April.
 - Where to find more information about me
   To find more information look on my linkedin profile or my website.
* Guidelines
 - 1 page
 - Readable format
 - Mention company several times
