* Notes
 - pick a tense
 - Action verbs
 - 1 page
 - clear language
* Contact Information
** Address
 - Is this really necessary
** Online
*** Email
 - russellshomberg@gmail.com
*** Website
 - http://russellshomberg.com
*** Linked In
*** GitHub
 - http://github.com/rshom
* Statement
  After serving five years in the Navy, reaching the rank of Leutenant, and fully qualifying as a Information Warfare Officer, I requested seperation to pursue a career in engineering. I am currently seeking a job to jumpstart such a career.
* Work Experience
** Cryptologic Warfare Officer
 - Navy Information Operations Command
 - Pearl Harbor, HI
 - DEC 2013 - DEC 2016
*** Direct Support Officer Sub-Surface - Primary Duty
- 4 operational deployments and 12 training missions on six seperate ships.
- Led 15 sailors and six equipment racks.
- 1 of 5 Department Heads, responsible for all operational planning.
- Sole Intelligence Officer in a radio-silent environment, responsible for evaluating risk vs reward in mission goals.
- Produced detailed reports and data packages viewed by high ranking officials including Chief of Naval Operations and the President.
- Selected by Command Cyber Fleet to evaluate submarines and cryptologic teamsfor deployment readiness. 
*** Division Officer
- Responsible for management of one of more divisions of approximently 40 sailors.
- Oversaw daily training and administrative functions.
- Scheduled deployment cycles based on available manning.
*** Department Action Officer
**** Acting Department Head
- Primary substitute for my Department Head during leave of other absenses.
- Responsible for over 400 sailors.
- Reported directly to NIOC Hawaii's Commanding Officer
**** Departmental Inspection Coordinator
- Selected to evaluate wellbeing of the entire structure and organization. 
- Designed and implemented new policies and practices 
- Establishing new internal duties and selected sailors to fill them.
**** Department/Command Representative
- Routinely selected to represent the command either as primary or to support as technical expert on operations and equipment
- Gave NSA/NIOC Hawaii tours and briefs to Admirals, Staff Officers, and other VIPs
- Represented my department and command in meetings with entities that either supported or depended on our operations.
**** Qualification Board Chair/Member (officer/enlisted)
- Acted as approval authority for enlisted subsurface training qualifications.
- Advised Commanding Officer on all Officer qualifications.
- Recognized as technical and operational training expert throughout command.
**** Qualification Programs.
- While working primary duties, completed four intensive self-driven qualification programs culminating in oral boards presented to senior officers.
- Battle Watch Captain (3 months), Cryptologic Warfare Officer (18 months), Direct Support Officer (2 deployments), and Information Warfare Community Officer (3 years).
*** Battle Watch Captain
- Led team of 9 sailors responsible for providing threat warning and time relevant intelligence reporting to forward deployed ships and aircraft.
- Proactively distrubuted information through intelligence and operational networks through formal briefs and reports, informal teleconferences, phone calls, emails, and in-person conversations.
- Provided NIOC Hawaii's Commanding Officer a daily hour long Operations Brief.
- Represented command in daily conference with the Commander of Cyber Fleet.
*** Junior Officer in Training
 - MAY 2012 - DEC 2013
 - Worked at multiple training commands leading such varied experiences as remodeling a wardroom, learning spanish, testing heavy cranes, and leading a parade.
**** Information Warfare Officer Basic Course, Pensacola, FL
**** Naval Facilities Command South East, Panama City, FL
**** Defense Language Institute, Monterey, CA
**** NROTC Temporary Duty, Boston, MA
* Technical Skills
** Software
   I pick up computer programs very quickly. Usually I can learn compentancy of a new program within an hour and master it within a day.
 - Excel
   - Macros
   - Scripting
   - Charts
   - Pivot Tables
 - Word
 - Powerpoint
 - Windows/OSX/Linux
 - Emacs
 - VIM
 - GIT
 - Many more
** CAD
 - Solidworks
 - EagleCAD
** Programming & Networks
   I'm not a software developer, but I can write a program to solve a problem or automate a common task.
 - MATLAB
 - Python
   - MATPLOTLIB
   - SciPy
   - Panda
   - PyPlot
 - LaTex
 - Javascript
   - NodeJS
   - NPM
   - Express
   - Angular
   - Mongoose
 - BASH
 - SSH
 - C/C++
 - HTML/CSS
 - Bootstrap
 - PHP/MySQL
 - HTTP
 - LAMP Server
 - MEAN Server
 - PGP
** Electronics
   Only basic skills, but occasionally useful for some problem solving.
 - Simple circuit design
 - Soldering
 - Microprocessors
   - Arduino
   - Rasberry PI
 - DC Motors
** Machining and Building
   Mostly remodeling our house as a kid.
 - Metalwork
 - CNC, Lathe, Press
 - Woodwork
 - Simple construction
** Mathmatics/Engineering
 - Statistics
 - Calculus
 - Differential Equations
 - Statics
 - Dynamics
 - Mechanics of Materials
 - Fluid Dynamics
 - Thermodynamics
* Other Skills
** Project Management
 - Ran daily operations briefs and planning councils for multiple military commands.
 - Tactical advisor to Commanding Officers in information limited environments.
 - Scheduling
 - Manning
 - Budgeting
 - Setting guidelines
 - Risk mitigation
 - Resource Management
 - Deliverable Management
 - Time Management
** Collaboration
   Worked as part of countless diverse team of various sizes throughout time as a Naval Officer
   Regular integrated with officers and crews of submarines in situations which required collaborative planning within hours of stepping on board.
 - Followership
 - Teamwork
** Leadership and Management
   Operational and administrative leader to countless service men and women.
   Routinely selected for increased responcibility.
 - Deligate
 - Run and effective meeting
** Communication
   Comfortable speaking to and engaging with groups any size or rank.
 - Public Speaking
 - Building slides
 - Writing
** Fast Learning
   I pick up knew skills quickly.
* Profesional Certifications
** Commissioned LT US Navy Individual Ready Reserves
* Education
** Boston University 
*** BS Mechanical Engineering, May 2012
** Defense Language Institute
*** AA Spanish, April 2013
* Supporting documents
** FITREPS
 - Include all and maybe some note on how to read them.
** PIM from GREENVILLE
 - Note on what it is.
* Answers to questions
** Why didn't you do anything in the Navy for 2 years?
** Why did you get out of the navy?
** Why didn't you do anything after the Navy for 4 months?
